#!/usr/local/bin/node --harmony
var errorArr = [];
global.exitERR = function(err, warn){
    var stack = util ? util.stack().join("\n    ") : "";
    if(err) {
        failed = 1;
        if(vc){
            err = err.replace(new RegExp(vc.base, 'g'), '');
        }
        if (stack) {
            err = err.trim();
            err += "\n    "+stack;
        }
        console.log("[publish2static] ERROR: "+err+"\n");
        errorArr.push("[publish2static] "+err);
    }
    if(warn) {
        if(vc){
            warn = warn.replace(new RegExp(vc.base, 'g'), '');
        }
        if (stack) {
            warn = warn.trim();
            warn += "\n    "+stack;
        }
        console.log("[publish2static] WARN: "+warn+"\n");
        errorArr.push("[publish2static] "+warn);
    }
    return err || warn;
}
var Reporter = require("./lib/reporter");
var reporter = new Reporter("publish2static", `dev.html`);
var fs = require('fs');
var request = require('request');
var iconv = require('iconv-lite');
var path = require('path');
var $$ = require('./lib/bowlder');
var util = require("./lib/util4go");
util.reporter = reporter;
var conf = util.conf;
var execSync = util.execSync;
var ENV = process.env;
var stage = ENV.GO_STAGE_NAME;
var label = ENV.GO_PIPELINE_LABEL || 0;
var vcver = ENV.GO_REVISION || 1;
var project = ENV.GO_PIPELINE_NAME;
var log = util.log;
var cloudEnv = global.cloudEnv = "omadDev";
var vc = util.vc;
//相对工作目录读写
var pwd = process.cwd();
var read = util.read;
var write = util.write;
var readWork = util.readWork;
var writeWork = util.writeWork;
//代码检查
var lintUtils = $$.map(conf.lint, arr=>$$.map(name=>{
    return require("./lintUtil/" + name);
}));
//数据目录
var infoDir = util.infoDir;
//备份目录
var backupDir = util.backupDir;
//临时目录
var tmpDir = util.tmpDir;
var htmlDir = util.distHtmlDir = util.getFolder(`${util.distDir}/html4dev`, true);  // var/fepack/dist/{project}/html4dev
var readHtml = read.bind(null, htmlDir);
var writeHtml = write.bind(null, htmlDir);
var projectJson = util.projectJson;

var distUtils = global.distUtils = {};
var distFns = [], packFns = [];
$$.each(projectJson.devDist || conf.devDist, json=>{
    if(typeof json == 'string') json = {type: json};
    var name = json.type;
    distUtils[name] = require("./distUtil/" + name);
    if(distUtils[name] && $$.isFunction(distUtils[name].publish)){
        distFns.push(distUtils[name].publish.bind(null, json));
    }
});
$$.each(conf.pack, name=>{
    var tmp = require("./packUtil/" + name);
    if(typeof tmp.dev == 'function'){
        packFns.push(tmp.dev);
    }
});
if(fs.existsSync(`${infoDir}/goscript/dist_dev.js`)){
    var _dist = require(`${infoDir}/goscript/dist_dev.js`);
    if($$.isFunction(_dist.publish)){
        distFns.push(_dist.publish);
    }
}

var failed = 0;

if(!/devQA/i.test(stage)){
    //在前端测试机上发布原始版本，让${devHost}/${path}/${res}生效
    if(vc.publish.dev){
        vc.publish.dev(vcver, vc.cdnfix+vc.path);
    }
    log("HTML例行检查", 2, 1);
    util.lsr(".", /\.s?html?$/).forEach(file => {
        util.stack(["出错文件: "+file]);
        if(/^\.\/modules|^\.\/goscript/.test(file)) { //忽略goscript目录
            return;
        }
        file = file.trim();
        var base = file.replace(/.*\//, '');
        if (/^\./.test(base)) {   //忽略隐藏文件
            return;
        }
        log(`Validating ${file}: `);
        var fatal = validHtml(file);
        if (fatal == '') {
            console.log("passed.");
        } else {
            failed = 1;
            console.log("failed.");
            global.exitERR(fatal);
        }
    });
    util.stack([]);
    
    log("CSS例行检查", 2, 1);
    util.lsr(".", /\.css$/).forEach(file => {
        file = file.trim();
        util.stack(["出错文件: "+file]);
        var base = file.replace(/.*\//, '');
        if (/^(\.|inventory)/.test(base)) {   //忽略隐藏文件
            return;
        }
        log(`Validating ${file}: `);
        var fatal = validCss(file);
        if (fatal == '') {
            console.log("passed.");
        } else {
            failed = 1;
            console.log("failed.");
            global.exitERR(fatal);
        }
    });
    util.stack([]);
}

util.printTime();

(async function(){
    await util.promise;
    log("复制源代码", 2, 1);
    await util.wander(function(dir){
        return util.isValidDir(dir);
    }, function(file, base){
        var flag = util.isValidFile(base);
        if (flag == 9) {    //(s)html,xml,json => html4dev/
            cpHtml(file, base);
        } else if(flag == 10) { //不发布到static服务器及cdn的其它文件 => static/
            cpRes(file, base);
        }
    });
    util.printTime();

    //publish to static.f2e.netease.com
    if(!/devQA/i.test(stage)){

        // 6. 扩展相对路径(仅后端项目)
        //if (util.syncTo || projectJson[cloudEnv] || ENV[cloudEnv]) {
            log(`处理${htmlDir}目录(parseSSI)`, 2, 1);
            parseSSI(htmlDir);     //内联所有外部ssi
            parseRes(htmlDir);     //处理资源路径
        //}
    }
    
     await Promise.all(packFns.map(fn => fn(htmlDir)));  //自定义打包流程: bowlder, vue, nej, regular...

    // 同步到后端服务器(非云主机)
    //if (util.syncTo || projectJson[cloudEnv] || ENV[cloudEnv]) {
        var rDir = util.syncTo && util.syncTo.static;
        util.proc4backend(htmlDir, rDir);
    //}

    // 10. 打包页面文件
    execSync(`cd ${htmlDir}; tar zcf ../html4dev.tar.gz *`);
    reporter.set("tarLink", `${conf.devHost2}/dist/${project}/html4dev.tar.gz`);

    await Promise.all(distFns.map(fn => fn()));

    reporter.set("toperr", errorArr.join("\n").replace(/</g, '&lt;').replace(/>/g, '&gt;'));
    reporter.save();

    process.exit(failed)
})();

function validHtml(file){
    var errors = [];
    var html = readWork(file);
    html = html.replace(/<!--[^\!].*?-->/g, '');
    var msgs = [];
    reporter.set("warnings[]", {
        url: util.fulldir(file),
        msgs: msgs
    });

    var count = {'link':0, 'script':0}; //css/js引用次数
    var result, patt = /(<(link|script).*? (?:href|src)=(.*?)(?= |>).*?>)/ig;
    while((result = patt.test(html))){
        count[result[2]] ++;
    }

    if(lintUtils){
        $$.each(lintUtils.html, linter => {
            var [errs, warns] = linter(html, util);
            errs.forEach(msg => {
                errors.push(msg);
            });
            warns.forEach(msg => {
                msgs.push(msg);
            });
        });
    }
    msgs.push(`CSS files: ${count.link}; JS files: ${count.script}`);
    return errors.map(msg => " - " + msg).join("\n");
}

function validCss(file){
    var content = readWork(file);
    var errors = [];
    var warnings = [];
    content = content.replace(/\/\*[\s\S]*?\*\//g, '');
    
    var basedir = path.dirname(path.resolve(`/${vc.cdnfix}${vc.path}`, file));
    var result, patt = /url\s*\(\s*(.*?)\s*\)/ig;
    while((result = patt.exec(content))){
        var link = result[1].replace(/['"]/g, '');
        if(/\.css$/.test(link) || /^\s*(about|data|https?):/i.test(link) || link.length > 200){
            continue;
        }
        //检查引用的文件是否存在
        link = link.replace(/[\?#].*?$/, '');
        var _file = util.fulldir(link, basedir);
        if(!/^\//.test(_file)){
            continue;
        }
        if(vc.exist && !vc.exist(_file)){
            errors.push(`${file} 中引用的 ${_file} 不存在`);
        }
    }
    
    if(lintUtils){
        $$.each(lintUtils.css, linter => {
            var [errs, warns] = linter(content, util);
            errs.forEach(msg => {
                errors.push(msg);
            });
            warns.forEach(msg => {
                warnings.push(msg);
            });
        });
    }
    if(errors.length){
        reporter.set("errors[]", {
            url: util.fulldir(file),
            msgs: errors
        });
    }
    if(warnings.length || !errors.length){
        reporter.set("warnings[]", {
            url: util.fulldir(file),
            msgs: warnings
        });
    }
    return errors.map(msg => " - " + msg).join("\n");
}

/*
* 转换dir下文件中的地址为static(conf.devHost)地址(fulldir);
* @param dir {string} 目录
* @param clear {bool} 是否清除meta[cmd_id]标签
*
* 实际dir传入的为html4dev, 该目录下只有 html/xml/json文件。
* */
function parseRes(dir, clear){ // 处理代码中的资源地址(改为绝对路径)  //dir=>html4dev
    log(`[parseRes] ${dir}`, 2, 1);
    util.lsr(dir).forEach(file => {
        if(util.isPreserved(file)){
            return;
        }
        
        log(`Parsing ${file}:\n`);
        var ext = path.extname(file);
        if (fs.existsSync(file) && !util.binaryReg.test(ext)) {
            var html = readWork(file);
            //对于非ssi碎片，改变fulldir()所用的相对路径
            var tmppath = path.dirname(file);
            if (tmppath != dir && /<html|#header/i.test(html)) {    // html4dev/的孙子目录 && 包含<html|#header  : 主文件
                tmppath = tmppath.replace(new RegExp(tmpDir + `/[^/]*?/`), "");
                if (tmppath) { //不是项目根目录
                    global.VCPATH = vc.path+"/"+tmppath;
                }
            } 
            if(ext == ".json"){
                // 替换: "*/*-*.*.js"  "*/*-*.css"  (*为\w)  ==> fulldir()
                html = html.replace(/"([\w\/\-\.]*?\.(js|css))"/g, (all, m1) => '"'+util.fulldir(m1)+'"');
            }else{
                html = util.expandFullPath(html);
            }
            if(clear){
                html = html.replace(/\s*<meta\s+name="cms_id"[\s\S]*?>\s*/ig, "\n"); //避免暴露cmsid
            }

            writeWork(file, html);
            global.VCPATH = vc.path;
        }
    });
}

//递归分析ssi,返回ssi对应的html   (删除其中的meta[cms_id]标签)
function inlineSSI(file, relroot){
    var ssifile = file;
    relroot = relroot.replace(new RegExp(tmpDir + `/[^/]*`), "/"+vc.cdnfix+vc.path);
    //只接受/开头的路径
    if(!/^\//.test(ssifile)){   // ssi 不是/开头
        if (/^\//.test(relroot)) {  //relroot是/开头
            relroot = relroot.replace(vc.localhost, '');
            ssifile = path.resolve(relroot, ssifile);   //ssi替换为本地绝对路径。
        } else {
            global.exitERR("", "替换内联SSI出错: "+ssifile);
        }
    }
    // /vc.path/inc 本项目    /special/ cms
    if(ssifile.indexOf("/"+vc.cdnfix+vc.path+"/inc/") == 0
       || ssifile.indexOf("/special/") == 0){ //本项目或线上(cms)碎片
        return `<!--#include file="${file}"-->`;
    }
    var reldir = path.dirname(ssifile);
    var html;
    //ssi的可能性
    //  1. /special/  绝对路径  cms内容
    //  2. inc/xx      相对路径 当前项目下内容
    //  3  /sports/testgo  绝对路径， 对应svn路径。
    if(ENV.GO_TEST || ~ssifile.indexOf(vc.cdnfix+vc.path)){ //ssi包含 vc.cdnfix+vc.path ,视作本项目内容
        //场景:  inc/xx的ssi,在之前会被替换为绝对路径，指向/var/fepack/dist/{project}/html4dev/ssi下的文件。
        html = readWork(path.resolve(vc.localhost, ssifile));
    }else{
        html = execSync(`svn cat ${vc.host}${ssifile} ${vc.auth}`);
    }
    if(!html){
        global.exitERR("", `SSI文件 ${ssifile} 不存在或为空(${file}, ${relroot})。`);
        return `<!--#include file="${file}"-->`;
    }
    html = html.replace(/<!--#include\s+(file|virtual)=(['"])(\S*?)\2\s*-->/ig, (all, m1, m2, m3) => inlineSSI(m3, reldir))
        .replace(/<meta\s+name="cms_id".*?>\s*/ig, '');
    return html;
}

//清除_group属性，
//<!--\\#include  转换为:  <!--#include
//如果存在util.syncTo, 则内联所有ssi  (本地: /vc.path/ 和 cms: /special/ 的ssi不内联)
function parseSSI(path){ //替换跨频道SSI  // path => /var/.../html4dev
    log("[publish2static] 替换跨频道SSI("+path+")", 2, 1);
    util.lsr(path, /\.s?html/).forEach(file => {
        file = file.trim();
        util.stack(`出错文件: ${file}`);
        var content = readWork(file);
        log(`处理${file}中的SSI..\n`);
        var relroot = file.replace(vc.localhost, '/');
        if(util.syncTo && conf.vc.type != 'git'){   //内联所有跨项目的ssi(/、modules、widget或../开头都要替换)
            //group3: 匹配 include标签里，
            //      以/、modules、widget、../开头的    file|virtual 属性值。
            content = content.replace(/<!--#include\s+(file|virtual)\s*=\s*(["'])((\/|widget|modules|\.\.\/)\S*?)\2\s*-->/ig, (all, m1, m2, m3) => inlineSSI(m3, relroot));
        }
        content = content.replace(/ _group="\S+"/g, '');

        content = content.replace(/<!--\\#include\s+(file|virtual)=/ig, "<!--#include $1=");
        writeWork(file, content);
        util.stack([]);
    });
}

function cpHtml(file, base){
    var dir = path.dirname(file);
    var odir = util.getFolder(`${htmlDir}/${dir}`);
    if(projectJson.skipRes && /(^|\/)(modules|widget)(\/|$)/.test(dir)){
        return;
    }
    if(projectJson.whiteList && !projectJson.whiteList[base]){
        return;
    }
    if(projectJson.blackList && (projectJson.blackList[base] || projectJson.blackList[dir])){
        return;
    }
    util.cpFile(file, odir);
}

function cpRes(file, base){
    var dir = path.dirname(file);
    var odir = util.getFolder(`${util.distStaticDirs[0]}/${dir}`);
    if(projectJson.skipRes && /(^|\/)(modules|widget)(\/|$)/.test(dir)){
        return;
    }
    util.cpFile(file, odir);
}
